In [1]:
import pandas as pd
emb = pd.read_csv("politician_embedding.csv")
emb

0         1         2         3         4         5         6  \
0    -0.004742  0.195250  0.462723  0.504912 -0.346100  0.240062 -0.335112   
1     0.230850  0.286152  0.233551  0.256156 -0.308969 -0.243003 -0.245095   
2    -0.362057 -0.055521  0.091740 -0.364959 -0.257696 -0.476093 -0.501335   
3    -0.283273  0.295539  0.379047 -0.506663 -0.366593 -0.028546  0.503836   
4    -0.163252 -0.319116 -0.252986 -0.350014 -0.228978 -0.388825 -0.421866   
...        ...       ...       ...       ...       ...       ...       ...   
5903  0.349977  0.206881  0.121352  0.108730  0.081701  0.136530  0.431430   
5904  0.205474  0.166048  0.358791  0.299162 -0.120707 -0.201508 -0.041370   
5905 -0.307714 -0.218867  0.186829  0.400600 -0.268654  0.562671  0.205958   
5906  0.486643  0.061825 -0.272198 -0.477592  0.056850  0.436851 -0.015897   
5907 -0.298034  0.126997  0.209450 -0.325802 -0.128498 -0.366550 -0.440254   

             7         8         9        10        11        12        13  \
0     0.344381  0.023588 -0.332543 -0.486879  0.232037  0.097171 -0.141813   
1    -0.281883 -0.434795 -0.299478 -0.325266 -0.196964  0.103781  0.095245   
2    -0.172721  0.192389 -0.211863  0.182231 -0.252932 -0.195526 -0.276594   
3    -0.142373  0.408848  0.133970 -0.124139  0.196644  0.106386  0.146099   
4     0.215424  0.313512 -0.219980  0.253863 -0.357193 -0.315502  0.244742   
...        ...       ...       ...       ...       ...       ...       ...   
5903  0.367053 -0.336297  0.158573  0.100805  0.421194  0.208838  0.442634   
5904 -0.512942 -0.555056 -0.178221 -0.154642  0.220520 -0.134389  0.367065   
5905  0.396834  0.221304  0.307869 -0.178668 -0.124738 -0.213121  0.274568   
5906 -0.125517  0.241650  0.200351 -0.170119  0.367305 -0.274469  0.382177   
5907 -0.300752  0.216675 -0.102867  0.205831 -0.199841 -0.128561 -0.429417   

            14        15  
0     0.281754 -0.364205  
1    -0.407022 -0.311009  
2     0.166088  0.463809  
3    -0.157984  0.007255  
4     0.314421  0.256029  
...        ...       ...  
5903 -0.322749  0.028968  
5904  0.279016 -0.110312  
5905 -0.231483 -0.241057  
5906 -0.380776  0.104088  
5907 -0.000009  0.427297  

[5908 rows x 16 columns]

In [2]:
edges = pd.read_csv("politician_edges.csv")
edges

node_1  node_2
0           0    1972
1           0    5111
2           0     138
3           0    3053
4           0    1473
...       ...     ...
41724    5871    5873
41725    5879    5888
41726    5882    5899
41727    5882    5898
41728    5886    2981

[41729 rows x 2 columns]

In [3]:
edge_df = pd.DataFrame(edges)

In [4]:
edge_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41729 entries, 0 to 41728
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   node_1  41729 non-null  int64
 1   node_2  41729 non-null  int64
dtypes: int64(2)
memory usage: 652.1 KB


In [5]:
edge_df

node_1  node_2
0           0    1972
1           0    5111
2           0     138
3           0    3053
4           0    1473
...       ...     ...
41724    5871    5873
41725    5879    5888
41726    5882    5899
41727    5882    5898
41728    5886    2981

[41729 rows x 2 columns]

In [6]:
import csv
import numpy as np


num_nodes = 5908
a = np.zeros((num_nodes,num_nodes))
  
for i in range(5908):
    node1 = edge_df.loc[i ,"node_1"]
    node2 = edge_df.loc[i,"node_2"]
    a[node1][node2] = 1
    a[node2][node1] = 1

In [7]:
a

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [8]:
a[0][5111]

1.0

In [9]:
emb['ID'] = range(0, 5908)


print(emb)

             0         1         2         3         4         5         6  \
0    -0.004742  0.195250  0.462723  0.504912 -0.346100  0.240062 -0.335112   
1     0.230850  0.286152  0.233551  0.256156 -0.308969 -0.243003 -0.245095   
2    -0.362057 -0.055521  0.091740 -0.364959 -0.257696 -0.476093 -0.501335   
3    -0.283273  0.295539  0.379047 -0.506663 -0.366593 -0.028546  0.503836   
4    -0.163252 -0.319116 -0.252986 -0.350014 -0.228978 -0.388825 -0.421866   
...        ...       ...       ...       ...       ...       ...       ...   
5903  0.349977  0.206881  0.121352  0.108730  0.081701  0.136530  0.431430   
5904  0.205474  0.166048  0.358791  0.299162 -0.120707 -0.201508 -0.041370   
5905 -0.307714 -0.218867  0.186829  0.400600 -0.268654  0.562671  0.205958   
5906  0.486643  0.061825 -0.272198 -0.477592  0.056850  0.436851 -0.015897   
5907 -0.298034  0.126997  0.209450 -0.325802 -0.128498 -0.366550 -0.440254   

             7         8         9        10        11        1

In [10]:
import numpy as np

# Create a sample adjacency matrix
adj_matrix = a

# Calculate the degree of each node
degree = np.sum(adj_matrix, axis=1)

# Sort the degree in descending order and get the top 100 nodes
top_nodes = np.argsort(degree)[::-1][:100]

# Print the top 100 nodes with their degree
for i in top_nodes:
    print(f'Node {i} has degree {degree[i]}')


Node 147 has degree 157.0
Node 98 has degree 145.0
Node 1324 has degree 142.0
Node 112 has degree 141.0
Node 175 has degree 118.0
Node 191 has degree 118.0
Node 210 has degree 112.0
Node 277 has degree 104.0
Node 169 has degree 77.0
Node 190 has degree 71.0
Node 192 has degree 66.0
Node 195 has degree 64.0
Node 55 has degree 58.0
Node 121 has degree 55.0
Node 361 has degree 54.0
Node 93 has degree 54.0
Node 178 has degree 52.0
Node 179 has degree 50.0
Node 92 has degree 50.0
Node 108 has degree 50.0
Node 61 has degree 49.0
Node 155 has degree 49.0
Node 165 has degree 48.0
Node 18 has degree 48.0
Node 46 has degree 48.0
Node 3042 has degree 45.0
Node 4992 has degree 45.0
Node 426 has degree 44.0
Node 0 has degree 44.0
Node 72 has degree 40.0
Node 154 has degree 39.0
Node 395 has degree 39.0
Node 408 has degree 37.0
Node 113 has degree 37.0
Node 4 has degree 37.0
Node 211 has degree 36.0
Node 403 has degree 36.0
Node 423 has degree 36.0
Node 69 has degree 36.0
Node 44 has degree 36.0
Nod

In [11]:
top_nodes

array([ 147,   98, 1324,  112,  175,  191,  210,  277,  169,  190,  192,
        195,   55,  121,  361,   93,  178,  179,   92,  108,   61,  155,
        165,   18,   46, 3042, 4992,  426,    0,   72,  154,  395,  408,
        113,    4,  211,  403,  423,   69,   44,  208,  297,  384,   74,
        355,  143,  319,   77,  399,  420,  383,  302,   57,   79,  396,
         97,   88,  100,  256,  419,  329,  220,   11,  123,  309,  188,
        342,  173,   39, 5800,  136,   84,  371,  430,   89, 1864,  125,
        202,  346,  132, 3022,  298,  412,  138, 1744,  218,  388,  377,
        160,   56,  156,  393,  103,   85,  109,  316,    1,  394, 4032,
        391], dtype=int64)

In [12]:
S_nodes = top_nodes
S_nodes

array([ 147,   98, 1324,  112,  175,  191,  210,  277,  169,  190,  192,
        195,   55,  121,  361,   93,  178,  179,   92,  108,   61,  155,
        165,   18,   46, 3042, 4992,  426,    0,   72,  154,  395,  408,
        113,    4,  211,  403,  423,   69,   44,  208,  297,  384,   74,
        355,  143,  319,   77,  399,  420,  383,  302,   57,   79,  396,
         97,   88,  100,  256,  419,  329,  220,   11,  123,  309,  188,
        342,  173,   39, 5800,  136,   84,  371,  430,   89, 1864,  125,
        202,  346,  132, 3022,  298,  412,  138, 1744,  218,  388,  377,
        160,   56,  156,  393,  103,   85,  109,  316,    1,  394, 4032,
        391], dtype=int64)

In [13]:
S_nodes.shape

(100,)

In [14]:

arr = np.arange(0, 5908)
arr

array([   0,    1,    2, ..., 5905, 5906, 5907])

In [15]:
T_nodes = np.setdiff1d(arr, S_nodes)
T_nodes

array([   2,    3,    5, ..., 5905, 5906, 5907])

In [16]:
T_nodes.shape

(5808,)

In [17]:
emb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5908 entries, 0 to 5907
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       5908 non-null   float64
 1   1       5908 non-null   float64
 2   2       5908 non-null   float64
 3   3       5908 non-null   float64
 4   4       5908 non-null   float64
 5   5       5908 non-null   float64
 6   6       5908 non-null   float64
 7   7       5908 non-null   float64
 8   8       5908 non-null   float64
 9   9       5908 non-null   float64
 10  10      5908 non-null   float64
 11  11      5908 non-null   float64
 12  12      5908 non-null   float64
 13  13      5908 non-null   float64
 14  14      5908 non-null   float64
 15  15      5908 non-null   float64
 16  ID      5908 non-null   int64  
dtypes: float64(16), int64(1)
memory usage: 784.8 KB


In [18]:
import pandas as pd
import numpy as np


df = emb


id_array = S_nodes

S_emb = df[df['ID'].isin(id_array)]

print(S_emb)


             0         1         2         3         4         5         6  \
0    -0.004742  0.195250  0.462723  0.504912 -0.346100  0.240062 -0.335112   
1     0.230850  0.286152  0.233551  0.256156 -0.308969 -0.243003 -0.245095   
4    -0.163252 -0.319116 -0.252986 -0.350014 -0.228978 -0.388825 -0.421866   
11    0.448401 -0.100008 -0.278928 -0.274102 -0.361854  0.094360  0.086471   
18    0.212506 -0.139126  0.235434 -0.017737  0.464792  0.294492  0.151779   
...        ...       ...       ...       ...       ...       ...       ...   
3022  0.072388 -0.302130 -0.257105 -0.278137 -0.417244  0.337572  0.144256   
3042  0.225296 -0.319330 -0.189311 -0.250755 -0.363880  0.220870  0.158987   
4032  0.496453 -0.200248 -0.151651 -0.344689  0.068391  0.315489  0.233639   
4992  0.524934  0.167671  0.232966  0.142875 -0.004315  0.376891 -0.175281   
5800 -0.422827  0.366200 -0.225639 -0.007633  0.074640  0.716764 -0.279894   

             7         8         9        10        11        1

In [19]:
import pandas as pd
import numpy as np


df = emb


id_array = T_nodes


T_emb = df[df['ID'].isin(id_array)]

print(T_emb)

             0         1         2         3         4         5         6  \
2    -0.362057 -0.055521  0.091740 -0.364959 -0.257696 -0.476093 -0.501335   
3    -0.283273  0.295539  0.379047 -0.506663 -0.366593 -0.028546  0.503836   
5    -0.053556  0.228153  0.329264 -0.173395 -0.301294  0.260194  0.610191   
6     0.139397  0.321960 -0.479688  0.389282 -0.127617 -0.072553 -0.232355   
7     0.425108  0.320468 -0.201609 -0.280341  0.423013 -0.395022 -0.280457   
...        ...       ...       ...       ...       ...       ...       ...   
5903  0.349977  0.206881  0.121352  0.108730  0.081701  0.136530  0.431430   
5904  0.205474  0.166048  0.358791  0.299162 -0.120707 -0.201508 -0.041370   
5905 -0.307714 -0.218867  0.186829  0.400600 -0.268654  0.562671  0.205958   
5906  0.486643  0.061825 -0.272198 -0.477592  0.056850  0.436851 -0.015897   
5907 -0.298034  0.126997  0.209450 -0.325802 -0.128498 -0.366550 -0.440254   

             7         8         9        10        11        1

In [20]:
S_emb1 = S_emb.drop(['ID'], axis=1)
T_emb1 = T_emb.drop(['ID'], axis=1)

ILM = np.dot(S_emb1,T_emb1.T)  
ILM

array([[-2.41849093e-01, -1.05599567e-01,  6.52447869e-03, ...,
         4.66956621e-01, -4.28965745e-01, -2.55423073e-01],
       [-9.27975046e-02, -1.14471888e-01, -1.70898937e-01, ...,
        -1.35995793e-01, -1.91874066e-01, -2.36665321e-02],
       [ 1.00826017e+00, -1.63472543e-01,  2.01084622e-03, ...,
        -2.25273200e-01, -1.22001145e-01,  6.21116497e-01],
       ...,
       [-5.44111901e-01, -1.91094767e-01, -1.16537055e-01, ...,
         1.21852429e-01,  3.04486295e-01, -4.39285233e-01],
       [-5.09303006e-01, -2.42458925e-01,  9.09456106e-04, ...,
         7.17204404e-02, -8.53109445e-02, -4.06513863e-01],
       [-2.19110902e-01, -2.43024706e-01,  7.30198559e-02, ...,
         3.83691578e-01,  1.59406544e-01, -2.07423375e-01]])

In [21]:
ILM.shape

(100, 5808)

In [22]:
def softmax_(x):
    return np.exp(x)/np.sum(np.exp(x))
ILM = np.apply_along_axis(softmax_, 1, ILM)
ILM

array([[1.27458757e-04, 1.46063632e-04, 1.63394318e-04, ...,
        2.58940564e-04, 1.05707536e-04, 1.25740324e-04],
       [1.50657485e-04, 1.47427210e-04, 1.39338680e-04, ...,
        1.44287907e-04, 1.36446471e-04, 1.61441027e-04],
       [4.62926627e-04, 1.43428386e-04, 1.69240241e-04, ...,
        1.34832761e-04, 1.49501624e-04, 3.14324188e-04],
       ...,
       [8.46540721e-05, 1.20492842e-04, 1.29819894e-04, ...,
        1.64767855e-04, 1.97783186e-04, 9.40098799e-05],
       [9.72351689e-05, 1.26973264e-04, 1.61959277e-04, ...,
        1.73843577e-04, 1.48580148e-04, 1.07761625e-04],
       [1.19761105e-04, 1.16931134e-04, 1.60393429e-04, ...,
        2.18831374e-04, 1.74865379e-04, 1.21169028e-04]])

In [23]:

ILM.shape

(100, 5808)

In [24]:
import numpy as np
import pandas as pd

# create a 100x5808 array
arr = ILM

# flatten the array into a 1D array
linear_arr = arr.flatten()

# create a DataFrame with the linear array and two column names
df = pd.DataFrame({'Values': linear_arr})

# add a column for the row values
df['Rowvalue'] = np.repeat(np.arange(100), 5808)

# add a column for the column values
df['Columnvalue'] = np.tile(np.arange(5808), 100)

# print the DataFrame
print(df)


          Values  Rowvalue  Columnvalue
0       0.000127         0            0
1       0.000146         0            1
2       0.000163         0            2
3       0.000160         0            3
4       0.000135         0            4
...          ...       ...          ...
580795  0.000149        99         5803
580796  0.000141        99         5804
580797  0.000219        99         5805
580798  0.000175        99         5806
580799  0.000121        99         5807

[580800 rows x 3 columns]


In [25]:
import numpy as np


arr = T_nodes

# repeat the array 100 times along the first axis
repeated_arr = np.tile(arr, (100, 1))

# flatten the repeated array into a 1D array
result_arr = repeated_arr.flatten()

# print the shape of the result array
print("Result array shape:", result_arr.shape)

df['Columnvalue'] = result_arr

# print the updated DataFrame
print(df)


Result array shape: (580800,)
          Values  Rowvalue  Columnvalue
0       0.000127         0            2
1       0.000146         0            3
2       0.000163         0            5
3       0.000160         0            6
4       0.000135         0            7
...          ...       ...          ...
580795  0.000149        99         5903
580796  0.000141        99         5904
580797  0.000219        99         5905
580798  0.000175        99         5906
580799  0.000121        99         5907

[580800 rows x 3 columns]


In [26]:
import numpy as np

# create an example array
arr = S_nodes
sorted_arr = np.sort(arr)
# repeat each element 5808 times successively
new_arr = np.repeat(sorted_arr, 5808)

# print the new array
print(new_arr)


[   0    0    0 ... 5800 5800 5800]


In [27]:
new_arr.shape

(580800,)

In [28]:
df['Rowvalue'] = new_arr

# print the updated DataFrame
print(df)

          Values  Rowvalue  Columnvalue
0       0.000127         0            2
1       0.000146         0            3
2       0.000163         0            5
3       0.000160         0            6
4       0.000135         0            7
...          ...       ...          ...
580795  0.000149      5800         5903
580796  0.000141      5800         5904
580797  0.000219      5800         5905
580798  0.000175      5800         5906
580799  0.000121      5800         5907

[580800 rows x 3 columns]


In [29]:
df.info

<bound method DataFrame.info of           Values  Rowvalue  Columnvalue
0       0.000127         0            2
1       0.000146         0            3
2       0.000163         0            5
3       0.000160         0            6
4       0.000135         0            7
...          ...       ...          ...
580795  0.000149      5800         5903
580796  0.000141      5800         5904
580797  0.000219      5800         5905
580798  0.000175      5800         5906
580799  0.000121      5800         5907

[580800 rows x 3 columns]>

In [30]:
array1 = np.zeros((5908,5908))
array1

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [31]:
for i in range(len(df)):
  array1[df.loc[i,'Rowvalue'], df.loc[i,'Columnvalue']] = df.loc[i,'Values']

array1

array([[0.        , 0.        , 0.00012746, ..., 0.00025894, 0.00010571,
        0.00012574],
       [0.        , 0.        , 0.00015066, ..., 0.00014429, 0.00013645,
        0.00016144],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [32]:
array1[0,0]

0.0

In [33]:
array1[array1 == 0.0] = 0.00000001
array1

array([[1.00000000e-08, 1.00000000e-08, 1.27458757e-04, ...,
        2.58940564e-04, 1.05707536e-04, 1.25740324e-04],
       [1.00000000e-08, 1.00000000e-08, 1.50657485e-04, ...,
        1.44287907e-04, 1.36446471e-04, 1.61441027e-04],
       [1.00000000e-08, 1.00000000e-08, 1.00000000e-08, ...,
        1.00000000e-08, 1.00000000e-08, 1.00000000e-08],
       ...,
       [1.00000000e-08, 1.00000000e-08, 1.00000000e-08, ...,
        1.00000000e-08, 1.00000000e-08, 1.00000000e-08],
       [1.00000000e-08, 1.00000000e-08, 1.00000000e-08, ...,
        1.00000000e-08, 1.00000000e-08, 1.00000000e-08],
       [1.00000000e-08, 1.00000000e-08, 1.00000000e-08, ...,
        1.00000000e-08, 1.00000000e-08, 1.00000000e-08]])

In [34]:
array1.shape

(5908, 5908)

In [35]:
import csv

a = array1

with open("new_file.csv","w+") as my_csv:
    csvWriter = csv.writer(my_csv,delimiter=',')
    csvWriter.writerows(a)